package com.usagin.juicecraft.Init.sounds;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

import static com.usagin.juicecraft.JuiceCraft.MODID;
import static net.minecraftforge.registries.ForgeRegistries.SOUND_EVENTS;

public class AlteSoundInit {
    public static final DeferredRegister<SoundEvent> ALTE_SOUNDS = DeferredRegister.create(SOUND_EVENTS, MODID);
    public static final RegistryObject<SoundEvent> ALTE_SPARK = registerFriendSoundEvent("alte_spark");
    public static final RegistryObject<SoundEvent> ALTE_ANGRY = registerFriendSoundEvent("alte_angry");
    public static final RegistryObject<SoundEvent> ALTE_ATTACK_0 = registerFriendSoundEvent("alte_attack_0");
    public static final RegistryObject<SoundEvent> ALTE_ATTACK_1 = registerFriendSoundEvent("alte_attack_1");
    public static final RegistryObject<SoundEvent> ALTE_ATTACK_2 = registerFriendSoundEvent("alte_attack_2");
    public static final RegistryObject<SoundEvent> ALTE_ATTACK_3 = registerFriendSoundEvent("alte_attack_3");
    public static final RegistryObject<SoundEvent> ALTE_ATTACK_4 = registerFriendSoundEvent("alte_attack_4");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_0 = registerFriendSoundEvent("alte_battle_0");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_1 = registerFriendSoundEvent("alte_battle_1");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_2 = registerFriendSoundEvent("alte_battle_2");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_3 = registerFriendSoundEvent("alte_battle_3");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_4 = registerFriendSoundEvent("alte_battle_4");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_5 = registerFriendSoundEvent("alte_battle_5");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_6 = registerFriendSoundEvent("alte_battle_6");
    public static final RegistryObject<SoundEvent> ALTE_BATTLE_7 = registerFriendSoundEvent("alte_battle_7");
    public static final RegistryObject<SoundEvent> ALTE_DEATH = registerFriendSoundEvent("alte_death");
    public static final RegistryObject<SoundEvent> ALTE_EQUIP_0 = registerFriendSoundEvent("alte_equip_0");
    public static final RegistryObject<SoundEvent> ALTE_EQUIP_1 = registerFriendSoundEvent("alte_equip_1");
    public static final RegistryObject<SoundEvent> ALTE_EQUIP_2 = registerFriendSoundEvent("alte_equip_2");
    public static final RegistryObject<SoundEvent> ALTE_EQUIP_3 = registerFriendSoundEvent("alte_equip_3");
    public static final RegistryObject<SoundEvent> ALTE_EVADE_0 = registerFriendSoundEvent("alte_evade_0");
    public static final RegistryObject<SoundEvent> ALTE_EVADE_1 = registerFriendSoundEvent("alte_evade_1");
    public static final RegistryObject<SoundEvent> ALTE_EVADE_2 = registerFriendSoundEvent("alte_evade_2");
    public static final RegistryObject<SoundEvent> ALTE_EVADE_3 = registerFriendSoundEvent("alte_evade_3");
    public static final RegistryObject<SoundEvent> ALTE_FLEE_0 = registerFriendSoundEvent("alte_flee_0");
    public static final RegistryObject<SoundEvent> ALTE_FLEE_1 = registerFriendSoundEvent("alte_flee_1");
    public static final RegistryObject<SoundEvent> ALTE_FLEE_2 = registerFriendSoundEvent("alte_flee_2");
    public static final RegistryObject<SoundEvent> ALTE_FLEE_3 = registerFriendSoundEvent("alte_flee_3");
    public static final RegistryObject<SoundEvent> ALTE_HEALING_0 = registerFriendSoundEvent("alte_healing_0");
    public static final RegistryObject<SoundEvent> ALTE_HEALING_1 = registerFriendSoundEvent("alte_healing_1");
    public static final RegistryObject<SoundEvent> ALTE_HEALING_2 = registerFriendSoundEvent("alte_healing_2");
    public static final RegistryObject<SoundEvent> ALTE_HEALING_3 = registerFriendSoundEvent("alte_healing_3");
    public static final RegistryObject<SoundEvent> ALTE_HURT_0 = registerFriendSoundEvent("alte_hurt_0");
    public static final RegistryObject<SoundEvent> ALTE_HURT_1 = registerFriendSoundEvent("alte_hurt_1");
    public static final RegistryObject<SoundEvent> ALTE_HURT_2 = registerFriendSoundEvent("alte_hurt_2");
    public static final RegistryObject<SoundEvent> ALTE_HURT_3 = registerFriendSoundEvent("alte_hurt_3");
    public static final RegistryObject<SoundEvent> ALTE_HYPER_EQUIP = registerFriendSoundEvent("alte_hyper_equip");
    public static final RegistryObject<SoundEvent> ALTE_HYPER_USE = registerFriendSoundEvent("alte_hyper_use");
    public static final RegistryObject<SoundEvent> ALTE_IDLE_0 = registerFriendSoundEvent("alte_idle_0");
    public static final RegistryObject<SoundEvent> ALTE_IDLE_1 = registerFriendSoundEvent("alte_idle_1");
    public static final RegistryObject<SoundEvent> ALTE_IDLE_2 = registerFriendSoundEvent("alte_idle_2");
    public static final RegistryObject<SoundEvent> ALTE_IDLE_3 = registerFriendSoundEvent("alte_idle_3");
    public static final RegistryObject<SoundEvent> ALTE_IDLE_NIGHT = registerFriendSoundEvent("alte_idle_night");
    public static final RegistryObject<SoundEvent> ALTE_INJURED_0 = registerFriendSoundEvent("alte_injured_0");
    public static final RegistryObject<SoundEvent> ALTE_INJURED_1 = registerFriendSoundEvent("alte_injured_1");
    public static final RegistryObject<SoundEvent> ALTE_INJURED_2 = registerFriendSoundEvent("alte_injured_2");
    public static final RegistryObject<SoundEvent> ALTE_INJURED_3 = registerFriendSoundEvent("alte_injured_3");
    public static final RegistryObject<SoundEvent> ALTE_INTERACT_0 = registerFriendSoundEvent("alte_interact_0");
    public static final RegistryObject<SoundEvent> ALTE_INTERACT_1 = registerFriendSoundEvent("alte_interact_1");
    public static final RegistryObject<SoundEvent> ALTE_INTERACT_2 = registerFriendSoundEvent("alte_interact_2");
    public static final RegistryObject<SoundEvent> ALTE_INTERACT_3 = registerFriendSoundEvent("alte_interact_3");
    public static final RegistryObject<SoundEvent> ALTE_LAUGH = registerFriendSoundEvent("alte_laugh");
    public static final RegistryObject<SoundEvent> ALTE_MODULE_EQUIP = registerFriendSoundEvent("alte_module_equip");
    public static final RegistryObject<SoundEvent> ALTE_PAT_0 = registerFriendSoundEvent("alte_pat_0");
    public static final RegistryObject<SoundEvent> ALTE_PAT_1 = registerFriendSoundEvent("alte_pat_1");
    public static final RegistryObject<SoundEvent> ALTE_PAT_2 = registerFriendSoundEvent("alte_pat_2");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_0 = registerFriendSoundEvent("alte_recovery_0");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_1 = registerFriendSoundEvent("alte_recovery_1");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_2 = registerFriendSoundEvent("alte_recovery_2");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_3 = registerFriendSoundEvent("alte_recovery_3");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_FAILED_0 = registerFriendSoundEvent("alte_recovery_failed_0");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_FAILED_1 = registerFriendSoundEvent("alte_recovery_failed_1");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_FAILED_2 = registerFriendSoundEvent("alte_recovery_failed_2");
    public static final RegistryObject<SoundEvent> ALTE_RECOVERY_FAILED_3 = registerFriendSoundEvent("alte_recovery_failed_3");
    public static final RegistryObject<SoundEvent> ALTE_WARNING_0 = registerFriendSoundEvent("alte_warning_0");
    public static final RegistryObject<SoundEvent> ALTE_WARNING_1 = registerFriendSoundEvent("alte_warning_1");
    public static final RegistryObject<SoundEvent> ALTE_WARNING_2 = registerFriendSoundEvent("alte_warning_2");
    public static final RegistryObject<SoundEvent> ALTE_WIN_0 = registerFriendSoundEvent("alte_win_0");
    public static final RegistryObject<SoundEvent> ALTE_WIN_1 = registerFriendSoundEvent("alte_win_1");
    public static final RegistryObject<SoundEvent> ALTE_WIN_2 = registerFriendSoundEvent("alte_win_2");
    public static final RegistryObject<SoundEvent> ALTE_WIN_3 = registerFriendSoundEvent("alte_win_3");
    public static final RegistryObject<SoundEvent> ALTE_DRAW = registerFriendSoundEvent("alte_draw");
    public static final RegistryObject<SoundEvent> ALTE_SHEATHE = registerFriendSoundEvent("alte_sheathe");
    public static final RegistryObject<SoundEvent> ALTE_ROD_START = registerFriendSoundEvent("alte_rod_start");
    public static final RegistryObject<SoundEvent> ALTE_PUNISHER = registerFriendSoundEvent("alte_punisher");
    public static final RegistryObject<SoundEvent> ALTE_PUNISHER_VOICE = registerFriendSoundEvent("alte_punisher_voice");
    public static final RegistryObject<SoundEvent> ALTE_SELFDESTRUCT = registerFriendSoundEvent("alte_selfdestruct");
    public static final RegistryObject<SoundEvent> ALTE_MINIGUN = registerFriendSoundEvent("alte_minigun");
    public static final RegistryObject<SoundEvent> ALTE_PANEL = registerFriendSoundEvent("alte_panel");
    public static final RegistryObject<SoundEvent> ALTE_HYPERSTART = registerFriendSoundEvent("alte_hyperstart");
    public static final RegistryObject<SoundEvent> ALTE_HYPERWINDUP = registerFriendSoundEvent("alte_hyperwindup");
    public static final RegistryObject<SoundEvent> ALTE_HYPERMINIGUNSPIN = registerFriendSoundEvent("alte_hyperminigunspin");
    public static final RegistryObject<SoundEvent> ALTE_HYPERRELAX = registerFriendSoundEvent("alte_hyperrelax");
    public static final RegistryObject<SoundEvent> ALTE_HYPEREND = registerFriendSoundEvent("alte_hyperend");
    public static final RegistryObject<SoundEvent> ALTE_SHOCKWAVE = registerFriendSoundEvent("alte_shockwave");

    public static RegistryObject<SoundEvent> registerFriendSoundEvent(String name) {

        return ALTE_SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(new ResourceLocation(MODID, name)));
    }
}
